spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/censusdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: POSTGRESQL
  flyway:
    locations: classpath:migration
    enabled: true
    check-location: false
aws:
  localstack:
    s3:
      url: http://localhost:14572
cloud:
  aws:
    region:
      auto: false
      static: us-west-2
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

com:
  org:
    census:
      migration:
        aws:
          region: us-west-2
        s3:
          bucketName: source-files
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html